# Render Blueprint for PayPals Project
# This file can be used to deploy the entire stack with one click

services:
  # PostgreSQL Database
  - type: pserv
    name: paypals-db
    env: node
    plan: free
    databases:
      - name: paypals
        user: paypals_user

  # Backend API Service
  - type: web
    name: paypals-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && node index.js
    rootDir: ./server
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: paypals-db
          property: connectionString
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      # Add your other environment variables manually in Render dashboard
      # - key: EMAIL_USER
      #   value: your-email@gmail.com
      # - key: EMAIL_PASSWORD
      #   value: your-app-password
      # - key: GOOGLE_MAPS_API_KEY
      #   value: your-api-key

  # Frontend Static Site
  - type: web
    name: paypals-frontend
    env: static
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: ./client/paypals
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://paypals-backend.onrender.com/api